### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by feamsr00** [pyrech/composer-notifier#4]
Hi!
Any chance of dusting this off and updating this?

**Comment by pyrech** [comment]
Would you mind to submit a PR updating the lib? 🙂

If not, I can try to find some times in the coming days to give it a try.

**Comment by feamsr00** [comment]
"Coming days" is fine. I think it just needed the plugin version bumped. Maybe?

**Comment by pyrech** [comment]
FYI I just released v1.1 which add compatibility with recent Composer :slightly_smiling_face:

**Comment by feamsr00** [comment]
It works!
